-- BTC Autonomous Research Engine v1. Isolated research tables; no APEX production rule is activated.
create table if not exists public.btc_research_runs(id uuid primary key default gen_random_uuid(),mission text not null,status text not null check(status in('QUEUED','RUNNING','PAUSED','STOPPED','COMPLETE','BLOCKED','BUDGET_EXHAUSTED')),phase text not null check(phase in('LITERATURE','REPLICATION','EXPERIMENT','RED_TEAM','DIRECTOR','PARITY')),budget_usd numeric(12,4) not null check(budget_usd>0),spent_usd numeric(12,6) not null default 0 check(spent_usd>=0),cycle_no integer not null default 0 check(cycle_no>=0),notes text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.btc_research_events(id bigint generated always as identity primary key,run_id uuid not null references public.btc_research_runs(id) on delete cascade,event_type text not null,payload jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.btc_research_usage(id bigint generated always as identity primary key,run_id uuid not null references public.btc_research_runs(id) on delete cascade,provider text not null,model text not null,role text not null,input_tokens bigint not null default 0,output_tokens bigint not null default 0,web_searches integer not null default 0,cost_usd numeric(12,6) not null default 0,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.btc_research_literature(id uuid primary key default gen_random_uuid(),run_id uuid not null references public.btc_research_runs(id) on delete cascade,topic text not null,title text not null,url text not null,source_type text not null,quality_tier text not null check(quality_tier in('A','B','C')),published_date text,research_question text not null,claim text not null,method text not null,dataset_period text,timeframe text,costs_included boolean,leakage_risks jsonb not null default '[]'::jsonb,replication_value text not null check(replication_value in('HIGH','MEDIUM','LOW')),tags jsonb not null default '[]'::jsonb,created_at timestamptz not null default now(),unique(run_id,url));
create table if not exists public.btc_research_experiments(id uuid primary key default gen_random_uuid(),run_id uuid not null references public.btc_research_runs(id) on delete cascade,experiment_id text,spec_hash text not null,hypothesis text not null,status text not null,spec jsonb not null,result jsonb not null default '{}'::jsonb,critic jsonb,director_decision jsonb,rejection_reason text,created_at timestamptz not null default now(),unique(run_id,spec_hash));
create table if not exists public.btc_research_decisions(id bigint generated always as identity primary key,run_id uuid not null references public.btc_research_runs(id) on delete cascade,experiment_id text,decision jsonb not null,created_at timestamptz not null default now());
create table if not exists public.btc_research_promotion_packages(id uuid primary key default gen_random_uuid(),run_id uuid not null references public.btc_research_runs(id) on delete cascade,experiment_id text not null,signal_name text not null,status text not null check(status in('PENDING_PARITY','PARITY_PASSED','SHADOW_APPROVED','REJECTED')),contract_hash text not null unique,package jsonb not null,created_at timestamptz not null default now(),unique(run_id,experiment_id));
create index if not exists btc_research_events_run_created_idx on public.btc_research_events(run_id,created_at desc);create index if not exists btc_research_usage_run_created_idx on public.btc_research_usage(run_id,created_at desc);create index if not exists btc_research_literature_run_tier_idx on public.btc_research_literature(run_id,quality_tier,created_at desc);create index if not exists btc_research_experiments_run_status_idx on public.btc_research_experiments(run_id,status,created_at desc);create index if not exists btc_research_promotions_run_status_idx on public.btc_research_promotion_packages(run_id,status,created_at desc);
alter table public.btc_research_runs enable row level security;alter table public.btc_research_events enable row level security;alter table public.btc_research_usage enable row level security;alter table public.btc_research_literature enable row level security;alter table public.btc_research_experiments enable row level security;alter table public.btc_research_decisions enable row level security;alter table public.btc_research_promotion_packages enable row level security;
revoke all on table public.btc_research_runs,public.btc_research_events,public.btc_research_usage,public.btc_research_literature,public.btc_research_experiments,public.btc_research_decisions,public.btc_research_promotion_packages from public,anon,authenticated;
grant select,insert,update,delete on table public.btc_research_runs,public.btc_research_events,public.btc_research_usage,public.btc_research_literature,public.btc_research_experiments,public.btc_research_decisions,public.btc_research_promotion_packages to service_role;grant usage,select on all sequences in schema public to service_role;
