substitutions:
  _REGION: asia-northeast3
  _SERVICE: agora3
  _JOB: btc-research-job
  _AR_REPO: cloud-run-source-deploy
steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/btc-research-engine:$COMMIT_SHA", "."]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/btc-research-engine:$COMMIT_SHA"]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: ["run","deploy","${_SERVICE}","--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/btc-research-engine:$COMMIT_SHA","--region=${_REGION}","--platform=managed","--no-allow-unauthenticated","--update-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID,CLOUD_RUN_REGION=${_REGION},CLOUD_RUN_RESEARCH_JOB=${_JOB},GIT_SHA=$COMMIT_SHA,ENVIRONMENT=prod"]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: ["run","jobs","deploy","${_JOB}","--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/btc-research-engine:$COMMIT_SHA","--region=${_REGION}","--command=python","--args=job.py","--task-timeout=28800s","--max-retries=1","--update-env-vars=GIT_SHA=$COMMIT_SHA,ENVIRONMENT=prod"]
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/btc-research-engine:$COMMIT_SHA"
